# version: 1
# services:
#   - type: web
#     name: boust-ai-portal
#     env: python
#     plan: free
#     buildCommand: pip install -r requirements.txt
#     startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0



services:
  - type: web
    name: bou-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
